title: Scacci Vox
email: cpmachado@protonmail.com
description: >-
    A new movement in chess and engineering to fight for progress.
    A decentralized, anti dogmatic, and idealist approach to the great game.
baseurl: ""
url: "https://scaccivox.github.io"
twitter_username: scaccivox
github_username:  scaccivox

markdown: kramdown
remote_theme: no-style-please

theme_config:
    back_home_text: ".."

favicon: "./logo.png"

plugins:
  - jekyll-feed

